### ISSUE TITLE
Too many process spawned by Postgres during rebuild/verification

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3659] opened 2019-05-17 12:48 UTC
### Expected behavior
Postgres should not spawn too many connections
### Actual behavior
When i run rebuild/verification against `2.0.0-alpha.x` version node i see too many process spawned
```
lisk      7117  0.6  1.7 249660 140652 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35112) idle
lisk      7118  0.6  1.7 249908 141396 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35114) idle
lisk      7119  0.6  1.7 249532 142140 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35116) idle
lisk      7120  0.4  1.7 249908 143116 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35118) idle
lisk      7121  0.6  1.7 249532 140264 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35120) idle
lisk      7122  0.6  1.7 249532 140880 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35122) idle
lisk      7123  0.6  1.7 249908 140968 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35124) idle
lisk      7124  0.6  1.7 249908 140676 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35126) idle
lisk      7125  0.6  1.7 249908 141704 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35128) idle
lisk      7126  0.6  1.7 249532 141372 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35130) idle
lisk      7127  0.6  1.7 249532 142024 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35132) idle
lisk      7128  0.5  1.7 249532 141236 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35134) idle
lisk      7129  1.0  1.7 252200 144256 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35136) idle
lisk      7130  1.0  1.7 252224 144536 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35138) idle
lisk      7131  0.5  1.5 249912 130156 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35140) idle
lisk      7132  0.6  1.7 249532 140800 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35142) idle
lisk      7133  0.6  1.7 249532 140520 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35144) idle
lisk      7134  0.6  1.7 249908 139980 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35146) idle
lisk      7135  0.6  1.7 249532 140528 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35148) idle
lisk      7136  0.6  1.7 249532 142252 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35150) idle
lisk      7137  0.6  1.7 249532 141016 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35152) idle
lisk      7138  0.6  1.7 249532 140300 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35154) idle
lisk      7139  0.6  1.7 249660 141088 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35156) idle
lisk      7140  0.6  1.6 249908 132956 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35158) idle
lisk      7141  0.6  1.7 249908 141220 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35160) idle
lisk      7142  0.6  1.7 249908 140440 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35162) idle
lisk      7143  1.4  1.7 252256 145024 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35164) idle
lisk      7144  0.6  1.7 249532 140396 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35166) idle
lisk      7145  0.6  1.7 249532 141564 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35168) idle
lisk      7146  0.6  1.7 249532 140428 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35170) idle
lisk      7147  1.1  1.7 252256 144244 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35172) idle
lisk      7148  1.2  1.7 252000 144704 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35174) idle
lisk      7149  0.6  1.7 249532 140176 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35176) idle
lisk      7150  0.6  1.6 249908 137792 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35178) idle
lisk      7151  2.1  1.7 252260 145068 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35180) idle
lisk      7152  0.6  1.6 249908 137704 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35182) idle
lisk      7153  1.6  1.7 252380 146232 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35184) idle
lisk      7154  0.6  1.7 249532 141316 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35186) idle
lisk      7155  0.6  1.7 250072 144372 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35188) idle
lisk      7156  1.3  1.7 252200 145560 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35190) idle
lisk      7157  0.5  1.6 249908 136428 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35192) idle
lisk      7158  1.0  1.7 252536 144252 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35194) SELECT
lisk      7159  0.6  1.7 249532 141132 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35196) idle
lisk      7160  0.8  1.7 252260 142812 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35198) idle
lisk      7161  0.7  1.7 252000 143876 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35200) idle
lisk      7162  0.6  1.7 249908 140648 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35202) idle
lisk      7163  0.6  1.7 249532 140172 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35204) idle
lisk      7164  0.8  1.7 252184 142832 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35206) idle
lisk      7165  0.6  1.7 249908 140704 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35208) idle
lisk      7166  0.5  1.7 249908 140456 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35210) idle
lisk      7167  0.6  1.7 250148 142132 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35212) SELECT
lisk      7168  0.6  1.7 250352 140992 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35214) idle
lisk      7169  0.6  1.7 249532 140820 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35216) idle
lisk      7170  0.6  1.7 249908 141052 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35218) idle
lisk      7171  0.6  1.7 249908 141488 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35220) idle
lisk      7172  0.6  1.7 249908 141396 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35222) idle
lisk      7173  0.6  1.7 249532 141448 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35224) idle
lisk      7174  0.6  1.7 249532 140796 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35226) idle
lisk      7175  0.9  1.7 252260 144172 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35228) idle
lisk      7176  0.6  1.7 249536 140604 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35230) idle
lisk      7177  2.1  1.7 252384 145524 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35232) idle
lisk      7178  0.6  1.7 249536 141232 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35234) idle
lisk      7179  0.6  1.5 249912 129880 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35236) idle
lisk      7180  0.6  1.7 249536 141240 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35238) idle
lisk      7181  0.5  1.7 249536 140632 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35240) idle
lisk      7182  0.5  1.7 249536 140460 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35242) idle
lisk      7183  0.6  1.7 252216 143764 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35244) idle
lisk      7184  0.5  1.7 249536 140568 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35246) idle
lisk      7185  0.5  1.6 249912 135596 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35248) idle
lisk      7186  0.5  1.7 249912 140456 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35250) idle
lisk      7187  0.5  1.7 249536 140664 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35252) idle
lisk      7188  0.5  1.6 249912 133264 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35254) idle
lisk      7189  0.6  1.7 249536 141568 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35256) idle
lisk      7190  0.6  1.7 249536 140188 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35258) idle
lisk      7191  0.6  1.7 249912 140640 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35260) idle
lisk      7192  0.5  1.6 249912 137128 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35262) idle
lisk      7193  0.6  1.7 249912 141644 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35264) idle
lisk      7194  0.6  1.7 249536 140164 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35266) idle
lisk      7195  6.3  1.8 252752 150556 ?       Ss   08:03   0:01 postgres: lisk lisk_main 127.0.0.1(35268) idle
lisk      7196  0.6  1.7 249536 140524 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35270) idle
lisk      7197  0.6  1.7 249536 140528 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35272) idle
lisk      7198  0.5  1.6 249912 138608 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35274) idle
lisk      7199  0.6  1.7 249536 140564 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35276) idle
lisk      7200  0.5  1.7 249536 140664 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35278) idle
lisk      7201  0.5  1.7 249536 141168 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35280) idle
lisk      7202  0.6  1.7 249536 142160 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35282) idle
lisk      7203  1.7  1.8 252696 148512 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35284) idle
lisk      7204  0.6  1.7 249536 141240 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35286) idle
lisk      7205  0.6  1.7 249820 142416 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35288) idle
lisk      7206  0.6  1.7 249536 140500 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35290) idle
lisk      7207  0.6  1.7 249536 140200 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35292) idle
lisk      7208  0.5  1.7 249536 140312 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35294) idle
lisk      7209  0.6  1.7 249536 141004 ?       Ss   08:03   0:00 postgres: lisk lisk_main 127.0.0.1(35296) idle
```
### Steps to reproduce
Deploy `2.0.0-alpha.x` node and run `node dist/index.js -n testnet -b 20000`
### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by michielmulders** [comment] 2019-05-17 16:08
While debugging this, I could not identify the source code spawning all these processes.
What I found:
- When reducing max connections for database, the total amount of connections (including the idle ones) matches the set max amount.
- `pgp_adapter.js:107` -> this.db.connect() gets called three times and also spawns idle connections.
- `process.js:291` -> when we cycle through all blocks with `async.eachSeries`, this spawns tons of idle processes when we set the limit to 95 connections (default value).

**Comment by michielmulders** [comment] 2019-05-17 16:19
When selecting all from `pgactivity` (`select * from pg_stat_activity;`) during the process, it shows that the idle connections try to insert the following data:

```sql
INSERT INTO mem_round ( "address","amount","delegate","round" ) VALUES ('6365926013346518016L','10000000000000000','af84ce3801a5e06fab2432f7a9ffa36d8a6e97948a2b40ca5a1ca0eb3f042dc2',1) ;
```



```sql
INSERT INTO mem_round ( "address","amount","delegate","round" ) VALUES ('6365926013346518016L','10000000000000000','0861e763bbe440691a13e22e104ec62e84f53df301e684cda445b84539dee695',1) ;
```

```sql
INSERT INTO mem_round ( "address","amount","delegate","round" ) VALUES ('6365926013346518016L','10000000000000000','c27e9e012f79e1d0bcbaceda19a13304c72105b3c4683791b49f6c84aa754da5',1) ;
```

All the queries are the same, it is every time the first transaction listed in the `transactions` array for Genesis account.

**Comment by michielmulders** [comment] 2019-05-20 10:14
Further research showed that the above result could not be reproduced and many idle connections spawn just for a period of 1-3 seconds. When reducing the `max_connections` property to only `5` instead of `95` (default), only 5 idle connections could be found in this time interval. The same abundance of idle connections occurs upon starting Lisk Core. The exact cause for this problem could not be identified and it is clearly not impacting performance/startup time of Lisk app/rebuilding process. For that reason, this issue will be closed.

**Comment by michielmulders** [comment] 2019-05-20 10:18
@vitaly-t Are you potentially aware of what is causing this issue? I was hinting at `pg-promise` doing some intelligent processing? :) Thanks!

**Comment by michielmulders** [comment] 2019-05-20 13:26
Or possibly:

```bash-shell
WARNING: Creating a duplicate database object for the same connection.
writer.js:66
    at PgpAdapter.connect (/Users/michiel.mulders/lisk/lisk-sdk/framework/src/components/storage/adapters/pgp_adapter.js:98:13)
    at Storage.bootstrap (/Users/michiel.mulders/lisk/lisk-sdk/framework/src/components/storage/storage.js:43:23)
    at module.exports (/Users/michiel.mulders/lisk/lisk-sdk/framework/src/modules/http_api/init_steps/bootstrap_storage.js:19:32)
    at HttpApi.bootstrap (/Users/michiel.mulders/lisk/lisk-sdk/framework/src/modules/http_api/http_api.js:142:9)
```

**Comment by vitaly-t** [comment] 2019-05-20 15:13
> Or possibly:
> WARNING: Creating a duplicate database object for the same connection.

See https://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise, which explains why such a message may pop up.

**Comment by shuse2** [comment] 2019-05-31 08:28
Closing due to expected behavior

**Closed by shuse2** 2019-05-31 08:28 UTC
Labels: :dizzy: quality assurance, bug
