### ISSUE TITLE
Move processor registration logic to application layer

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#4236] opened 2019-09-09 13:54 UTC
### Description
Although the SDK can register a default block processor, Core should register the ones that are going to be in use for Lisk's own network.
### Motivation
The SDK should be unaware of custom block processor implementations used by client applications, hence block processor registration flow should be exposed to the outer application interface so different client applications can register their own processors.
### Acceptance Criteria
- A block processor can be easily registered from Core or any other client application that uses the SDK

**Comment by shuse2** [comment] 2019-09-11 08:17
Duplicate of #4140

**Closed by shuse2** 2019-09-11 08:17 UTC
Labels: type: duplicate
