### ISSUE TITLE
Multisignature transaction various critical problems

### ISSUE THREAD

**Issue by dakk** [LiskHQ/lisk-sdk#4299] opened 2019-09-24 07:44 UTC
### Expected behavior
When I send a multisignature transaction I expect three things:
- The transaction will be removed when it reaches the expiration
- Transactions remeains in the pool of all nodes since the expiration
- If I submit, sign and broadcast a multisig tx, I expect it won't appear again unsigned in the transaction pool

### Actual behavior
But with the lig and the gdt multisignature wallets, we are experiencing various very critical problem; 
- we created a multisig tx, broadcasted unsigned, signed and broadcasted, but after few days an identical multisig transaction appeared again
- sometimes a valid unsigned transaction is not present in every node, sometimes appear and sometimes disappear
- an already expired unsigned multisig transaction appeared again after 1 week

### Steps to reproduce
These are random behaviors; I'm not sure how to deterministically reproduce them

### Which version(s) does this affect? (Environment, OS, etc...)
lisk-core latest version (and previous)

**Comment by corsaro1** [comment] 2019-09-24 07:47
yes, true. After 24h a multisignature tx is not fully signed (just partially signed) then it should expire and disappear totally from nodes. Instead we find these partially signed multisignature tx for days and days, disappearing from cache, then reappearing again randomly

**Comment by shuse2** [comment] 2019-09-26 12:39
@dakk @corsaro1 
Thank you for the report.
I think the described behavior is correct per current protocol.
If my understanding of the issue is correct, partially signed multisignature transaction is expiring after 24h, but it appears again and again.

This can happen if someone sends the transaction again to the network.
This is because the transaction is `valid` and the timer of the expiry is not defined in the protocol.
Therefore, each node will decide if it needs to be expired or not, and if the transaction is re-introduced in the network, it will start counting the multisignature expiry again since they received again.

This issue will be addressed in the below LIP.
https://github.com/LiskHQ/lips/blob/master/proposals/lip-0017.md

**Comment by dakk** [comment] 2019-09-27 07:54
This explains almost all of our problems @shuse2 , thank you ; the other problem we got is that pending multisig transactions appear and disappear from the pending set without any reason

**Comment by shuse2** [comment] 2019-09-27 07:57
Disappearing from the pending API endpoint is that when the system receives new block which contains the transactions, which has the same sender as the multisignature, it will be moved back to validated queue to re-verify the transaction.

**Comment by dakk** [comment] 2019-09-27 07:59
ok @shuse2 so the correct approach would be to check both pending and validated sets?

**Comment by shuse2** [comment] 2020-02-29 11:47
Superseded by #4836

**Closed by shuse2** 2020-02-29 11:47 UTC
Labels: elements/transaction-pool, elements/transactions, framework/node, type: bug
