### ISSUE TITLE
Network problems regarding peers for BFT branch

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#4189] opened 2019-09-03 09:38 UTC
### Expected behavior
The branch `feature/introduce_bft_consensus` has problems syncing to the network as it cannot find delegates. The full log can be found at the bottom of the issue.

### Actual behavior
When running core with `LISK_NETWORK=mainnet LISK_CONSOLE_LOG_LEVEL=debug node dist/index.js | npx bunyan -o short` for mainnet it should be able to sync up to the network.

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/introduce_bft_consensus`

```sh
❯ LISK_NETWORK=mainnet LISK_CONSOLE_LOG_LEVEL=debug node dist/index.js | npx bunyan -o short

08:48:36.011Z  INFO lisk-framework: Booting the application with Lisk Framework(0.1.0) (module=lisk-controller)
08:48:36.014Z  INFO lisk-framework: Starting the app - lisk-mainnet-8000 (module=lisk-controller)
08:48:36.015Z  INFO lisk-framework: Initializing controller (module=lisk-controller)
08:48:36.026Z  INFO lisk-framework: Loading controller (module=lisk-controller)
08:48:36.119Z  INFO lisk-framework: Old PID: 78016 (module=lisk-controller)
08:48:36.119Z  INFO lisk-framework: Current PID: 78590 (module=lisk-controller)
08:48:36.520Z  INFO lisk-framework: Loading module lisk-framework-chain:0.1.0 with alias "chain" (module=lisk-controller)
08:48:36.523Z DEBUG lisk-framework: Initiating cache... (module=chain)
08:48:36.526Z DEBUG lisk-framework: Initiating storage... (module=chain)
08:48:36.540Z DEBUG lisk-framework: Cache not enabled (module=chain)
08:48:36.544Z  INFO lisk-framework: Modules ready and launched (module=chain)
08:48:50.346Z DEBUG lisk-framework: Summing round - 1 (genesis block) (module=chain)
08:48:50.347Z DEBUG lisk-framework: Performing forward tick (module=chain)
08:48:50.440Z DEBUG lisk-framework: Updating ranks of all delegates... (module=chain)
08:48:50.452Z  INFO lisk-framework: Rebuilding block (module=chain, blockId=13658550407518916215, height=1)
08:48:50.458Z  INFO lisk-framework: Event network:bootstrap was subscribed but not registered to the bus yet. (module=lisk-controller)
08:48:50.459Z  INFO lisk-framework: Event network:ready was subscribed but not registered to the bus yet. (module=lisk-controller)
08:48:50.459Z  INFO lisk-framework: Event network:event was subscribed but not registered to the bus yet. (module=lisk-controller)
08:48:50.459Z  INFO lisk-framework: Module ready with alias: chain(lisk-framework-chain:0.1.0) (module=lisk-controller)
08:48:50.460Z  INFO lisk-framework: Loading module lisk-framework-network:0.1.0 with alias "network" (module=lisk-controller)
08:48:50.505Z  INFO lisk-framework: Module ready with alias: network(lisk-framework-network:0.1.0) (module=lisk-controller)
08:48:50.505Z  INFO lisk-framework: Loading module lisk-framework-http-api:0.1.0 with alias "http_api" (module=lisk-controller)
08:48:50.506Z  INFO lisk-framework: Module ready with alias: http_api(lisk-framework-http-api:0.1.0) (module=lisk-controller)
08:48:50.506Z  INFO lisk-framework: (module=lisk-controller)
    Bus listening to events [ 'app:ready',
      'app:state:updated',
      'chain:bootstrap',
      'chain:blocks:change',
      'chain:transactions:confirmed:change',
      'chain:signature:change',
      'chain:transactions:change',
      'chain:rounds:change',
      'chain:multisignatures:signature:change',
      'chain:multisignatures:change',
      'chain:delegates:fork',
      'chain:loader:sync',
      'chain:dapps:change',
      'chain:registeredToBus',
      'chain:loading:started',
      'chain:loading:finished',
      'network:bootstrap',
      'network:event',
      'network:ready',
      'network:registeredToBus',
      'network:loading:started',
      'network:loading:finished',
      'http_api:registeredToBus',
      'http_api:loading:started',
      'http_api:loading:finished' ]
08:48:50.507Z  INFO lisk-framework: (module=lisk-controller)
    Bus ready for actions [ 'app:getComponentConfig',
      'app:getApplicationState',
      'app:updateApplicationState',
      'chain:calculateSupply',
      'chain:calculateMilestone',
      'chain:calculateReward',
      'chain:getRoundDelegates',
      'chain:updateForgingStatus',
      'chain:postSignature',
      'chain:getForgingStatusForAllDelegates',
      'chain:getTransactionsFromPool',
      'chain:getTransactions',
      'chain:getSignatures',
      'chain:postTransaction',
      'chain:getDelegateBlocksRewards',
      'chain:getSlotNumber',
      'chain:calcSlotRound',
      'chain:getNodeStatus',
      'chain:getLastBlock',
      'chain:blocks',
      'chain:getHighestCommonBlockId',
      'network:request',
      'network:emit',
      'network:getPeers',
      'network:getPeersCount',
      'network:getUniqueOutboundConnectedPeersCount' ]
08:48:50.507Z  INFO lisk-framework: App started... (module=lisk-controller)
08:48:50.515Z DEBUG lisk-framework: Initiating cache... (module=http_api)
08:48:50.516Z DEBUG lisk-framework: Initiating storage... (module=http_api)
08:48:50.518Z DEBUG lisk-framework: Broadhash consensus: 0 % (module=chain)
08:48:50.519Z DEBUG lisk-framework: Cache not enabled (module=http_api)
08:48:50.520Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:48:50.923Z  INFO lisk-framework: Lisk started: 0.0.0.0:8000 (module=http_api)
08:48:50.954Z  INFO lisk-framework: Peer connect event: Connected to peer 94.237.93.169:8001 (module=network)
08:48:50.955Z DEBUG lisk-framework: Node connected to the network (module=network)
08:48:50.958Z  INFO lisk-framework: Loading transactions from the network (module=chain)
08:48:50.960Z  INFO lisk-framework: Sync time triggered (module=chain, syncing=false, lastReceipt=null)
08:48:50.960Z  INFO lisk-framework: Starting sync (module=chain)
08:48:50.961Z DEBUG lisk-framework: Establishing broadhash consensus before sync: 0 % (module=chain)
08:48:50.963Z  INFO lisk-framework: Peer connect event: Connected to peer 94.237.57.159:8001 (module=network)
08:48:50.974Z  INFO lisk-framework: Peer connect event: Connected to peer 94.237.46.150:8001 (module=network)
08:48:51.260Z  INFO lisk-framework: Peer connect event: Connected to peer 140.82.49.223:8001 (module=network)
08:48:51.340Z  INFO lisk-framework: Peer connect event: Connected to peer 45.77.71.214:8001 (module=network)
08:48:52.507Z DEBUG lisk-framework: Peer disconnect event: Outbound connection of peer 149.28.196.209:8001 was closed with code 4007 and reason: Client connection establishment timed out (module=network)
08:48:52.509Z DEBUG lisk-framework: Client connection establishment timed out (module=network)
08:48:52.961Z ERROR lisk-framework: Event response for 'rpc-request' timed out (module=network)
08:48:52.963Z ERROR lisk-framework: Event response for 'rpc-request' timed out (module=network)
08:48:52.963Z  WARN lisk-framework: Failed to load blocks from the network. (module=chain)
    error: {
      "name": "TimeoutError",
      "message": "Event response for 'rpc-request' timed out"
    }
08:48:52.964Z  INFO lisk-framework: Loading transactions from the network (module=chain)
08:48:52.975Z ERROR lisk-framework: Event response for 'rpc-request' timed out (module=network)
08:48:53.261Z ERROR lisk-framework: Event response for 'rpc-request' timed out (module=network)
08:48:53.343Z ERROR lisk-framework: Event response for 'rpc-request' timed out (module=network)
08:48:54.969Z  WARN lisk-framework: Failed to load blocks from the network. (module=chain)
    error: {
      "name": "TimeoutError",
      "message": "Event response for 'rpc-request' timed out"
    }
08:48:54.970Z  INFO lisk-framework: Loading transactions from the network (module=chain)
08:48:55.522Z DEBUG lisk-framework: Broadhash consensus: 0 % (module=chain)
08:48:56.971Z  WARN lisk-framework: Failed to load blocks from the network. (module=chain)
    error: {
      "name": "TimeoutError",
      "message": "Event response for 'rpc-request' timed out"
    }
08:48:56.973Z  INFO lisk-framework: Loading transactions from the network (module=chain)
08:48:58.973Z  WARN lisk-framework: Failed to load blocks from the network. (module=chain)
    error: {
      "name": "TimeoutError",
      "message": "Event response for 'rpc-request' timed out"
    }
08:48:58.975Z  INFO lisk-framework: Loading transactions from the network (module=chain)
08:49:00.523Z DEBUG lisk-framework: Broadhash consensus: 0 % (module=chain)
08:49:00.979Z ERROR lisk-framework: (module=chain)
    Unconfirmed transactions loader { TimeoutError: Event response for 'rpc-request' timed out
        at SCClientSocket._handleEventAckTimeout (/Users/michiel.mulders/lisk/lisk-sdk/elements/lisk-p2p/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
        at Timeout._onTimeout (/Users/michiel.mulders/lisk/lisk-sdk/elements/lisk-p2p/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10)
      name: 'TimeoutError',
      message: 'Event response for \'rpc-request\' timed out' }
08:49:00.980Z  INFO lisk-framework: Loading signatures from the network (module=chain)
08:49:00.981Z  WARN lisk-framework: Failed to load blocks from the network. (module=chain)
    error: {
      "name": "TimeoutError",
      "message": "Event response for 'rpc-request' timed out"
    }
08:49:00.981Z DEBUG lisk-framework: Establishing broadhash consensus after sync: 0 % (module=chain)
08:49:00.981Z  INFO lisk-framework: Finished sync (module=chain)
08:49:00.985Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:49:01.989Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:49:02.982Z  INFO lisk-framework: Loading signatures from the network (module=chain)
08:49:02.992Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:49:03.996Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:49:04.985Z  INFO lisk-framework: Loading signatures from the network (module=chain)
08:49:04.997Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:49:05.524Z DEBUG lisk-framework: Broadhash consensus: 0 % (module=chain)
08:49:05.998Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:49:06.544Z  INFO lisk-framework: Transaction pool - received size: 0 validated size: 0 verified size: 0 pending size: 0 ready size: 0 (module=chain)
08:49:06.988Z  INFO lisk-framework: Loading signatures from the network (module=chain)
08:49:06.999Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:49:07.999Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:49:08.989Z  INFO lisk-framework: Loading signatures from the network (module=chain)
08:49:09.004Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:49:10.008Z DEBUG lisk-framework: No delegates are enabled (module=chain)
08:49:10.526Z DEBUG lisk-framework: Broadhash consensus: 0 % (module=chain)
08:49:10.981Z  INFO lisk-framework: Sync time triggered (module=chain, syncing=false, lastReceipt=null)
08:49:10.984Z  INFO lisk-framework: Starting sync (module=chain)
08:49:10.984Z DEBUG lisk-framework: Establishing broadhash consensus before sync: 0 % (module=chain)
08:49:10.991Z ERROR lisk-framework: (module=chain)
    Signatures loader { TimeoutError: Event response for 'rpc-request' timed out
        at SCClientSocket._handleEventAckTimeout (/Users/michiel.mulders/lisk/lisk-sdk/elements/lisk-p2p/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
        at Timeout._onTimeout (/Users/michiel.mulders/lisk/lisk-sdk/elements/lisk-p2p/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10)
      name: 'TimeoutError',
      message: 'Event response for \'rpc-request\' timed out' }
08:49:12.988Z  WARN lisk-framework: Failed to load blocks from the network. (module=chain)
    error: {
      "name": "TimeoutError",
      "message": "Event response for 'rpc-request' timed out"
    }
^C
```

**Comment by shuse2** [comment] 2019-09-18 10:04
Closing because it's not reproducible

**Closed by shuse2** 2019-09-18 10:04 UTC
Labels: elements/P2P, type: bug, type: stretch goal
