### ISSUE TITLE
Require topics metadata for events

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-sdk#8084] opened 2023-01-26 06:50 UTC
### Description

Require the data mappings to the entries in the event `topics` to determine what entry is an address. Lisk Service can use this information to reliably and dynamically decode the addresses into `Lisk32` format.

### Motivation

- To present the user with decoded addresses in events.
- To index the events topic and enable querying of events based on the addresses in Lisk Service.

**Comment by shuse2** [comment] 2023-01-26 20:09
Duplicate of #7629

**Closed by shuse2** 2023-01-26 20:09 UTC
Labels: type: duplicate
