### ISSUE TITLE
Unable to start node while enabling the plugin

### ISSUE THREAD

**Issue by nagdahimanshu** [LiskHQ/lisk-sdk#7143] opened 2022-04-28 11:50 UTC
### Expected behavior
The node should be able to start with enabled plugins

### Actual behavior
Node crashes with the error while enabling these plugins `enable-forger-plugin` & `enable-report-misbehavior-plugin`.
```
13:43:24 INFO lisk-framework: Forging enabled on account: ee531c16f419b1fce5a86150ef5d755d90a062bb (module=lisk:app)
13:43:24 INFO lisk-framework: Forging enabled on account: 14785e33717634c91d63349ae1c0366c072be25c (module=lisk:app)
13:43:24 INFO lisk-framework: Forging enabled on account: 8ffd6d8167307044edaa5d61e5d89c5abdba41e8 (module=lisk:app)
13:43:24 INFO lisk-framework: Node ready and launched (module=lisk:app)
13:43:24 INFO lisk-framework: Starting controller (module=lisk:app)
13:43:24 INFO lisk-framework: forger Loading child-process plugin (module=lisk:app)
Error: Child process plugin loading timeout
13:43:27 INFO lisk-framework: Application shutdown started (module=lisk:app)
{
 "errorCode": 2,
 "message": "process.exit"
} 
```
### Steps to reproduce
Run node with forger plugin enabled

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by ishantiw** [comment] 2022-07-04 10:58
Getting below errors when up enabling plugins,

- **Dashboard plugin**
```js
index.js:17222 Uncaught Error: BLST bindings loader should only run in a NodeJS context: process.platform
    at A (index.js:17222:15)
    at r.getBinaryPath (index.js:17231:54)
    at 166../scripts/paths (index.js:16914:32)
    at a (index.js:1:629)
    at index.js:1:680
    at 168../bindings (index.js:16952:20)
    at a (index.js:1:629)
    at index.js:1:680
    at 167../lib (index.js:16942:14)
    at a (index.js:1:629)
```
- **MonitorPlugin**, **ReportMisbehaviorPlugin** and **ForgerPlugin**
```js
Message: RPC with IPC protocol must be enabled to use APIClient.
 Trace: Error: RPC with IPC protocol must be enabled to use APIClient.
    at MonitorPlugin.get apiClient [as apiClient] (/Users/ishantiwari/lisk-repos/sdk/node1/lisk-sdk/framework/src/plugins/base_plugin.ts:116:10)
    at MonitorPlugin.init (/Users/ishantiwari/lisk-repos/sdk/node1/lisk-sdk/framework-plugins/lisk-framework-monitor-plugin/src/monitor_plugin.ts:57:40)
    at Controller._loadInMemoryPlugin (/Users/ishantiwari/lisk-repos/sdk/node1/lisk-sdk/framework/src/controller/controller.ts:254:3)
    at Controller.start (/Users/ishantiwari/lisk-repos/sdk/node1/lisk-sdk/framework/src/controller/controller.ts:178:5)
```
- **Faucet Plugin**
```js
12:57:13 ERROR lisk-framework: Fail to start controller (module=lisk:app)
Message: Lisk validator found 3 error[s]:
Missing property, must have required property 'encryptedPassphrase'
Missing property, must have required property 'captchaSecretkey'
Missing property, must have required property 'captchaSitekey'
 Trace: Error: Lisk validator found 3 error[s]:
Missing property, must have required property 'encryptedPassphrase'
Missing property, must have required property 'captchaSecretkey'
Missing property, must have required property 'captchaSitekey'
    at FaucetPlugin.init (/Users/ishantiwari/lisk-repos/sdk/node1/lisk-sdk/framework/src/plugins/base_plugin.ts:130:11)
    at FaucetPlugin.init (/Users/ishantiwari/lisk-repos/sdk/node1/lisk-sdk/framework-plugins/lisk-framework-faucet-plugin/src/plugin/faucet_plugin.ts:36:15)
    at Controller._loadInMemoryPlugin (/Users/ishantiwari/lisk-repos/sdk/node1/lisk-sdk/framework/src/controller/controller.ts:254:16)
    at Controller.start (/Users/ishantiwari/lisk-repos/sdk/node1/lisk-sdk/framework/src/controller/controller.ts:178:5)
```

**Comment by shuse2** [comment] 2022-07-06 16:12
For `Dashboard plugin`, the issue is https://github.com/LiskHQ/lisk-sdk/issues/7140
For `MonitorPlugin, ReportMisbehaviorPlugin and ForgerPlugin`, I think the node is not running with `ipc` enabled?
For `Faucet Plugin`, it just requires the config in the plugin. so it is expected behavior

**Comment by ishantiw** [comment] 2022-07-08 08:18
For `MonitorPlugin`, `ReportMisbehaviorPlugin` and `ForgerPlugin`, its missing the ipc path in the config and it will be fixed in https://github.com/LiskHQ/lisk-sdk/issues/7277

**Closed by ishantiw** 2022-07-08 08:18 UTC
Labels: type: bug, framework
