### ISSUE TITLE
Ignore typescript projects from eslint

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#3411] opened 2019-04-18 12:53 UTC
### Expected behavior
It shouldn't
### Actual behavior
Eslint is taking in account transpiled files under `dist` folders
### Steps to reproduce
For example, go to `elements/lisk-transactions/dist-node` or `dist-browser` 
### Which version(s) does this affect? (Environment, OS, etc...)
`development`

**Comment by pablitovicente** [comment] 2019-08-13 08:39
I can't reproduce this. Please add more notes for it to be worked on.

**Comment by shuse2** [comment] 2019-08-13 20:35
I also double checked, and it's not reproducible. Therefore, closing this issue.

**Closed by shuse2** 2019-08-13 20:35 UTC
Labels: standards, type: enhancement, type: task
