### ISSUE TITLE
Lisk Commander cannot find module 'globby'

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk-sdk#5995] opened 2020-11-19 17:21 UTC
### Expected behavior

Lisk Commander works without throwing errors.

### Actual behavior

It's throwing errors all the time, when executing commands.
Examples are described below.

### Steps to reproduce

Install latest Commander
```
$ npm install --global --production lisk-commander@latest --registry https://npm.lisk.io
```

Calling commands results always in error, but the help is still displayed below.
```
$ lisk
(node:10279) [MODULE_NOT_FOUND] Error Plugin: lisk-commander: Cannot find module 'globby'
Require stack:
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/config/lib/plugin.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/config/lib/config.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/config/lib/index.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/command/lib/command.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/command/lib/index.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/bin/run
module: @oclif/config@1.14.0
task: not loading commands, globby not found
plugin: lisk-commander
root: /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander
See more details with DEBUG=*
A command line interface for Lisk

VERSION
  lisk-commander/5.0.0-alpha.1 darwin-x64 node-v12.18.4

USAGE
  $ lisk [COMMAND]

COMMANDS
  account     Commands relating to Lisk accounts.
  help        Displays help.
  message     Commands relating to user messages.
  passphrase  Commands relating to Lisk passphrases.
```

Calling other commands like `acocunt:create` fails completely

```
$ lisk account
(node:10306) [MODULE_NOT_FOUND] Error Plugin: lisk-commander: Cannot find module 'globby'
Require stack:
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/config/lib/plugin.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/config/lib/config.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/config/lib/index.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/command/lib/command.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/command/lib/index.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/bin/run
module: @oclif/config@1.14.0
task: not loading commands, globby not found
plugin: lisk-commander
root: /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander
See more details with DEBUG=*
Commands relating to Lisk accounts.

USAGE
  $ lisk account:COMMAND

$ lisk account:create
(node:10367) [MODULE_NOT_FOUND] Error Plugin: lisk-commander: Cannot find module 'globby'
Require stack:
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/config/lib/plugin.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/config/lib/config.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/config/lib/index.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/command/lib/command.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/node_modules/@oclif/command/lib/index.js
- /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander/bin/run
module: @oclif/config@1.14.0
task: not loading commands, globby not found
plugin: lisk-commander
root: /Users/mona/.nvm/versions/node/v12.18.4/lib/node_modules/lisk-commander
See more details with DEBUG=*
 ›   Error: command account:create not found
```

### Which version(s) does this affect? (Environment, OS, etc...)

- macOS Mojave
- Node 12.18.4, installed with `nvm`.
- Lisk Commander 5.0.0-alpha.1

**Comment by shuse2** [comment] 2020-11-24 16:12
https://github.com/oclif/oclif/issues/132#issuecomment-400476375

**Comment by shuse2** [comment] 2020-12-01 11:04
This was caused by the wrong publish process. It is resolved in public repo

**Closed by shuse2** 2020-12-01 11:04 UTC
Labels: type: bug
