### ISSUE TITLE
Inconsistency in vote

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#756] opened 2017-08-31 18:46 UTC
Referencing issue from Lisk-js
https://github.com/LiskHQ/lisk-js/issues/335

**Comment by Tosch110** [comment] 2017-09-29 14:06
`recipientId` should be `null` in vote transactions

**Comment by karek314** [comment] 2017-10-25 13:20
Issue in lisk-js has been closed, as it's related to lisk core, here it is
Why does [voting](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/vote.js#L41) require address to be specified while [second signature creation](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/signature.js#L53) or [delegate registration](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/delegate.js#L41) not?

**Comment by willclarktech** [comment] 2018-01-05 15:07
This is making things awkward in lisk-js where type 3 transactions have to be given special treatment. It would be much cleaner if `recipientId` could be `null` for all transactions where no balance is received.

Relevant lines are here:
https://github.com/LiskHQ/lisk/blob/7b5d1fa2c557913a244c191df5d2aa7e9cdb8ecd/logic/vote.js#L64-L66

**Comment by MaciejBaj** [comment] 2018-11-26 14:32
As the change is breaking, we cannot implement it without introducing a hard fork. The issue is included in our [Roadmap](https://lisk.io/roadmap) as part of "Security and Reliability". Suspended for now.

**Comment by shuse2** [comment] 2019-07-29 08:54
Closing because https://github.com/LiskHQ/lips/blob/master/proposals/lip-0012.md will solve this issue

**Closed by shuse2** 2019-07-29 08:54 UTC
Labels: framework/chain, status: icebox, status: suspended
