### ISSUE TITLE
Using Enum for similar CCM_STATUS_* constants

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7534] opened 2022-09-15 16:52 UTC
### Description

Currently we have a group of constants, all representing  CCM STATUS

```
export const CCM_STATUS_OK = 0;
export const CCM_STATUS_MODULE_NOT_SUPPORTED = 1;
export const CCM_STATUS_CROSS_CHAIN_COMMAND_NOT_SUPPORTED = 2;
export const CCM_STATUS_CHANNEL_UNAVAILABLE = 3;
export const CCM_STATUS_RECOVERED = 4;
```
We could instead use an Enum like this

```
Enum CCMStatus {
	OK,
	MODULE_NOT_SUPPORTED,
	CROSS_CHAIN_COMMAND_NOT_SUPPORTED,
	CHANNEL_UNAVAILABLE,
	RECOVERED
}
```
### Motivation
- a group of constants all conveying same meaning should be replaced with an Enum
- research team can use constants like shown above (in first case), but when we implement it in TypeScript, we can take advantage of language features to group them together

### Additional Information
- framework/src/modules/interoperability/constants.ts

**Comment by shuse2** [comment] 2022-11-10 07:59
Duplicate of #7520

**Closed by shuse2** 2022-11-10 07:59 UTC
Labels: type: duplicate
