### ISSUE TITLE
ease node.js version requirements

### ISSUE THREAD

**Issue by roccomuso** [LiskHQ/lisk-sdk#6678] opened 2021-08-23 13:58 UTC
### Description

Cannot use lisk-validator with higher versions of Node.js.

> @liskhq/lisk-validator@0.6.0: The engine "node" is incompatible with this module. Expected version ">=12.13.0 <=12". Got "14.16.0"

### Motivation

Usage with higher version of node.

**Comment by shuse2** [comment] 2021-08-31 13:12
Duplicate of #6552

**Closed by shuse2** 2021-08-31 13:12 UTC
Labels: type: duplicate
