### ISSUE TITLE
Assess default variables present in the network module

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-sdk#4442] opened 2019-10-29 09:38 UTC
### Description

`lisk-p2p` exposes many config variables for customization purposes. By default, we have shared them into the next file [network/defaults/config.ts](https://github.com/LiskHQ/lisk-sdk/blob/874c37e570858716c31e84d3777cdee5a5e5eee1/framework/src/modules/network/defaults/config.js#L147). Some of them might open security doors without adding any real value to `lisk-sdk` or `lisk-core`.

Also, in general, we should revisit the config and default value of the chain and http modules.

### Motivation

Network module focus only in the `lisk-p2p config variables which are relevant for `lisk-framework` and/or `lisk-core`. 

### Acceptance Criteria

Network module default config shows just a set of relevant variables.

**Comment by nazarhussain** [comment] 2019-12-05 11:06
@diego-G The config file you linked in the issue is not aligned with current development branch. Now only `wsPort` and `seedPeers` are there as default values.  

Is this issue still valid?

**Comment by diego-G** [comment] 2019-12-05 11:13
It is true that just the default mandatory values were left. But the issue still applies for the `maximum`|`minimum` values related to the checked properties and likely some others.

**Comment by shuse2** [comment] 2020-01-22 08:42
Should be removed as it is not configurable
- chain config / broadcasts
- forging force (default password already can detect the same behavior since there is no broadhash check)
- syncing active (syncying mechanism is different now)

**Comment by shuse2** [comment] 2020-01-22 08:55
Network module config is clean as of now, so I am closing this issue

**Closed by shuse2** 2020-01-22 08:55 UTC
Labels: framework
