### ISSUE TITLE
Update examples for transaction create command

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#7630] opened 2022-10-10 21:13 UTC
### Expected behavior

Update examples for transaction create command where tokenID should also be there.

### Actual behavior

tokenID is missing in the transaction:create command examples

### Steps to reproduce

n/a

### Which version(s) does this affect? (Environment, OS, etc...)

`6.0.0-alpha.4`

**Comment by shuse2** [comment] 2022-10-10 21:23
Duplicate of #7479

**Closed by shuse2** 2022-10-10 21:23 UTC
Labels: type: duplicate
