### ISSUE TITLE
Persist maxHeightPreviouslyForged in storage on block creation

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#4250] opened 2019-09-12 15:31 UTC
### Description
Acording to [LIP-0014](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md#additional-block-header-properties), `maxHeightPreviouslyForged` (worded `heightPrevious` in the document) needs to be persisted in storage.

One way to do this could be to use `ChainMeta` storage entity (`key/value`) to store and update a list of delegates by their publicKeys mapped to their `maxHeightPreviouslyForged` respective values.

For example:

key: `maxHeightPreviouslyForgedByDelegate`
value: 
```
{
  aDelegatePubKey: 0
}
```

Where `0` is the value for `maxHeightPreviouslyForged` for `aDelegatePubKey` delegate 

This can be done within the `create` pipeline in `block_processor_v2`

### Motivation
> If a delegate forges a block B to be added to the current chain, then B.heightPrevious must be the largest height at which the delegate forging the block previously forged a block on any chain or 0 if the delegate did not forge a block before. To be able to provide this information correctly, even in the case of node crashes, it is important that the largest height of a block previously forged is persistently stored before any forged block is broadcast to the network. 
### Acceptance Criteria
- Every time a block is `created` (doesn't necessarily mean it is successfully applied), `maxHeightPreviouslyForged` should be persisted in the database.

**Comment by shuse2** [comment] 2019-09-26 09:39
It's duplicate of #3696

**Closed by shuse2** 2019-09-26 09:39 UTC
Labels: framework, framework/chain
