### ISSUE TITLE
dyld[4780]: missing symbol called when importing lisk-client in node project

### ISSUE THREAD

**Issue by tomploem** [LiskHQ/lisk-sdk#8530] opened 2023-06-02 14:51 UTC
### Expected behavior

The following script for initiating a websocket client should resolve without errors. 

```
import { createWSClient } from "@liskhq/lisk-client";

const RPC_ENDPOINT = 'xyz';
let clientCache;

export const getClient = async () => {
  if (!clientCache) {
    clientCache = await createWSClient(RPC_ENDPOINT);
  }
  return clientCache;
};
```

### Actual behavior

The script for initiating a websocket client fails on execution with error `dyld[5585]: missing symbol called`. przemer found that this error could be related to M1 Macs that do not have the proper binary dependencies: https://gist.github.com/adrienjoly/e29a6e73fb7e701eefd80ff9bde9abeb

### Steps to reproduce

- Write a script that imports the lisk client in a node environment on a M1 Max

### Which version(s) does this affect? (Environment, OS, etc...)

MacOS Venture 13.4 - M1 Max

**Comment by mosmartin** [comment] 2023-07-11 11:48
Hi @tomploem, I trust you are well. I am currently looking into this and I see you are experiencing this issue on an M1 Max. I am currently on an M1 Pro and the same version of macOS as you. However, I am not able to replicate the issue (unsure if pro vs max is the reason). I also think that this is not an SDK issue per se but an issue nonetheless. 

 I'd like to check if you are still experiencing this as there has been a few updates since you posted the issue. 
 
 Thank you and will be glad to assist further.

**Comment by shuse2** [comment] 2023-08-03 07:55
Closing since we could not reproduce. Feel free to re-open with steps to reproduce the issue

**Closed by shuse2** 2023-08-03 07:55 UTC
Labels: status: invalid
