### ISSUE TITLE
Lisk 2.0.1 can start SSL-enabled Lisk-core without ssl certificate file

### ISSUE THREAD

**Issue by hitobb** [LiskHQ/lisk-sdk#4036] opened 2019-08-03 04:45 UTC
### Expected behavior

If Lisk software can not get ssl certificate file,it should stop the boot of lisk-core.

### Actual behavior

Lisk 2.0.1 can start SSL-enabled Lisk-core without ssl certificate file.

According to the log, after failing to open /ssl/lisk.key, the software is connecting to the wrong chain with height 8914319.
And it won't count up to 8914320 or later.

### Steps to reproduce
1. Set configuration to enable ssl in config.json

2. **Do not set ssl certificate files to the specified location** (in my case, I forgot to copy the files into the SSL folder)

3. Run ```bash lisk.sh start```

4. Lisk 2.0.1 can start SSL-enabled Lisk-core without ssl certificate file.

5. the software is connecting to the wrong chain with height 8914319.And it won't count up to 8914320 or later.

### Which version(s) does this affect? (Environment, OS, etc...)

Lisk core 2.0.1-rc0 on testnet

### Other

```
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"New peer found event: Discovered peer 46.101.218.57:7001","time":"2019-08-03T03:28:04.616Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":60,"msg":"System error: unhandledRejection : { message: 'ENOENT: no such file or directory, open \\'./ssl/lisk.key\\'',\n  stack:\n   'Error: ENOENT: no such file or directory, open \\'./ssl/lisk.key\\'\\n    at Object.openSync (fs.js:438:3)\\n    at Object.readFileSync (fs.js:343:35)\\n    at module.exports (/home/ubuntu/lisk-test/node_modules/lisk-framework/src/modules/http_api/init_steps/setup_servers.js:52:19)\\n    at HttpApi.bootstrap (/home/monamona/lisk-test/node_modules/lisk-framework/src/modules/http_api/http_api.js:109:13)' }","time":"2019-08-03T03:28:04.648Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Cleaning chain...","time":"2019-08-03T03:28:04.649Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Cleaning network...","time":"2019-08-03T03:28:04.652Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Cleanup controller...","time":"2019-08-03T03:28:04.649Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":50,"msg":"Reason: ENOENT: no such file or directory, open './ssl/lisk.key'","time":"2019-08-03T03:28:04.649Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Cleaned up successfully","time":"2019-08-03T03:28:04.651Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Saved all the peers to DB that have been tried","time":"2019-08-03T03:28:04.660Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Blocks 8914319","time":"2019-08-03T03:28:04.990Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Genesis block matched with database","time":"2019-08-03T03:28:04.991Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Validating current block with height 8914319","time":"2019-08-03T03:28:05.024Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Loader->validateBlock Validating block 2624920164477505116 at height 8914319","time":"2019-08-03T03:28:05.024Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Verify->verifyBlock succeeded for block 2624920164477505116 at height 8914319.","time":"2019-08-03T03:28:05.032Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Loader->validateBlock Validating block succeed for 2624920164477505116 at height 8914319.","time":"2019-08-03T03:28:05.032Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Finished validating the chain. You are at height 8914319.","time":"2019-08-03T03:28:05.033Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Blockchain ready","time":"2019-08-03T03:28:05.033Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Peer connect event: Connected to peer 188.166.100.144:7001","time":"2019-08-03T03:28:05.685Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"New peer found event: Discovered peer 188.166.100.144:7001","time":"2019-08-03T03:28:05.943Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Starting sync","time":"2019-08-03T03:28:14.621Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Finished sync","time":"2019-08-03T03:28:15.183Z","v":0}
```

**Comment by pablitovicente** [comment] 2019-08-05 12:51
Hello @hitobb, I've been looking into this and trying to replicate I see the error and the node eventually stopping (as the binary distribution uses pm2 for running it has a configuration of 10 restarts before completely stopping the node)

could you please run `bash lisk.sh status` in your installation and share the result?

**Comment by hitobb** [comment] 2019-08-05 15:42
Hi @pablitovicente

I reproduced the issue.
```
ubuntu@lisk99:~/lisk-test$ bash lisk.sh status
Lisk configured for testnet
[+] Lisk is running as PID: 22716
Current Block Height:  8936067
ubuntu@lisk99:~/lisk-test$
``` 
node ip address is 133.130.108.62
ssl configuration on config.json is this.
```
"ssl": {
         "enabled": true,
         "options": {
                     "port": 7171,
                      "address": "133.130.108.62"
                     }
 }
```
I will keep this environment.

**Comment by pablitovicente** [comment] 2019-08-05 15:49
Thanks for the update @hitobb I will test using the configuration you just shared.

**Comment by pablitovicente** [comment] 2019-08-05 15:52
@hitobb one more question, could you stop lisk, start it, wait five minutes and run the status again?

**Comment by hitobb** [comment] 2019-08-05 16:33
@pablitovicente 
I'll tell you the result
```
ubuntu@lisk99:~/lisk-test$
ubuntu@lisk99:~/lisk-test$ date
Tue Aug  6 01:17:35 JST 2019
ubuntu@lisk99:~/lisk-test$ bash lisk.sh stop
Lisk configured for testnet
[+] Lisk stopped successfully.
[+] Postgresql stopped successfully.
ubuntu@lisk99:~/lisk-test$
ubuntu@lisk99:~/lisk-test$ date
Tue Aug  6 01:17:53 JST 2019
ubuntu@lisk99:~/lisk-test$
ubuntu@lisk99:~/lisk-test$ bash lisk.sh start
Lisk configured for testnet
[+] Postgresql started successfully.
[+] Lisk started successfully.
[+] Lisk is running as PID: 24586
Current Block Height:  8936067
ubuntu@lisk99:~/lisk-test$
ubuntu@lisk99:~/lisk-test$ bash lisk.sh status
Lisk configured for testnet
[+] Lisk is running as PID: 24683
Current Block Height:  8936067
ubuntu@lisk99:~/lisk-test$ date
Tue Aug  6 01:20:53 JST 2019
ubuntu@lisk99:~/lisk-test$ bash lisk.sh status
Lisk configured for testnet
[+] Lisk is running as PID: 24878
Current Block Height:  8936067
ubuntu@lisk99:~/lisk-test$ date
Tue Aug  6 01:27:07 JST 2019
ubuntu@lisk99:~/lisk-test$ bash lisk.sh status
Lisk configured for testnet
[+] Lisk is running as PID: 24878
Current Block Height:  893606
ubuntu@lisk99:~/lisk-test$
```

**Comment by hitobb** [comment] 2019-08-05 16:39
It may need to rebuild the chain only once.
How about this.

1. Set configuration to enable ssl in config.json

2. **Do not set ssl certificate files to the specified location** (in my case, I forgot to copy the files into the SSL folder)

3. Run ```bash lisk.sh rebuild```

4. Lisk 2.0.1 can start SSL-enabled Lisk-core without ssl certificate file.

5. Run ```bash lisk.sh stop```

6. Run ```bash lisk.sh start```

7. I can not find the correct chain yet

**Comment by pablitovicente** [comment] 2019-08-06 08:21
@hitobb I'm setting the same configurations as you describe and still not able to reproduce (even with the last notes you posted) would you mind sharing your complete config (maybe obscuring any keys or other information you want to hide) and also share the last 500 lines of the logs in `logs/testnet/lisk.log` please?

**Comment by pablitovicente** [comment] 2019-08-06 08:29
Also could you run: 
- `source env.sh`
- `pm2 status`

and share the results? I'm wondering if another instance of Lisk might be running

**Comment by Nazgolze** [comment] 2019-08-06 08:38
133.130.108.62 seems to have caught up to the network, I'm seeing the current height at `http://133.130.108.62:7000/api/node/status`

**Comment by hitobb** [comment] 2019-08-06 09:25
@Nazgolze 

Sorry, the node has been restored. Make the issue state again

**Comment by pablitovicente** [comment] 2019-08-06 09:28
@hitobb ok. Let us know if you notice this again and we'll look further.

**Comment by hitobb** [comment] 2019-08-06 10:08
@pablitovicente 
Reproduced!
![forked](https://user-images.githubusercontent.com/14948578/62531525-99aa2c00-b87d-11e9-9dc9-73de503ddaf4.png)

**Comment by hitobb** [comment] 2019-08-06 10:33
@pablitovicente 

Please get the log file from here. I will remove the link after you get it.

https://drive.google.com/drive/folders/135-a33DFgospNwb8gRLnQKKoos4-_iUt?usp=sharing

**Comment by pablitovicente** [comment] 2019-08-06 11:24
@hitobb got them you can remove them. Thanks!

**Comment by hitobb** [comment] 2019-08-06 11:38
I will keep the node as the fork. Please let me know if you need additional logs.

**Comment by hitobb** [comment] 2019-08-07 14:26
@pablitovicente 

I heard that you could not reproduce this problem
Please get config.json file here.
I don’t change the location of the SSL certificate file in the config.json file. 
This may be the cause.

https://drive.google.com/drive/folders/135-a33DFgospNwb8gRLnQKKoos4-_iUt?usp=sharing

**Comment by pablitovicente** [comment] 2019-08-07 14:33
Hello @hitobb thanks for the file. I did use very similar options and still not able to reproduce. But I will try with this specific file.

**Comment by hitobb** [comment] 2019-08-07 15:48
Hello @pablitovicente 
This is how to reproduce from the correct chain.
```
ubuntu@lisk99:~/lisk-test$ bash lisk.sh status <--- [On Correct Chain]
Lisk configured for testnet
[+] Lisk is running as PID: 2168
Current Block Height:  8941182 
ubuntu@lisk99:~/lisk-test$ bash lisk.sh status
Lisk configured for testnet
[+] Lisk is running as PID: 2168
Current Block Height:  8941809 <--- [Count-up on Correct Chain]
ubuntu@lisk99:~/lisk-test$ bash lisk.sh stop
Lisk configured for testnet
[+] Lisk stopped successfully.
[+] Postgresql stopped successfully.
ubuntu@lisk99:~/lisk-test$ ls
bin               config       dist    include  lisk.sh           newrelic.js          package.json  README.md  scripts  tmp
blockchain.db.gz  config.json  env.sh  lib      lisk_snapshot.sh  node_modules         pgsql         redis      share    tune.sh
CHANGELOG.md      cron.log     etc     LICENSE  logs              npm-shrinkwrap.json  pids          REVISION   ssl      var
ubuntu@lisk99:~/lisk-test$ 
ubuntu@lisk99:~/lisk-test$ 
ubuntu@lisk99:~/lisk-test$ sudo rm -R ssl <--- [Point 1 : Erase SSL Certificate files]
[sudo] password for ubuntu: 
ubuntu@lisk99:~/lisk-test$ 
ubuntu@lisk99:~/lisk-test$ bash lisk.sh rebuild <--- [Point 2 : rebuild]
```

**Comment by pablitovicente** [comment] 2019-08-14 12:39
This was cleared up through discord. Closing.

**Closed by pablitovicente** 2019-08-14 12:39 UTC
Labels: framework, type: bug
