### ISSUE TITLE
Fees based on bytes written to db

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#476] opened 2017-03-14 17:45 UTC
Byte amount stored in db * transaction type constant = fee.

It also would be nice to add additional factor to calculate fee along with those 2 mentioned before based on median transactions count made in past blocks. Which would make sending transactions cheaper while blockchain is not being used much at time and discourage from making transactions while blockchain is being used more intense - in result it can cause self regulated stability over time. 

Fee can also depend on median transaction amount in x past block, which can reflect current Lisk price, while price is growing higher single transaction amount decreases.

**Comment by Phoenix1969** [comment] 2017-03-25 23:32
Sounds like an excellent idea

**Comment by karmacoma** [comment] 2017-04-21 15:53
Closing as duplicate of: #34

**Comment by karek314** [comment] 2017-04-21 16:46
Sort of, however here are more reasonable solutions while NN might be overkill while using standard algorithms will work as well.

**Comment by karmacoma** [comment] 2017-04-21 16:53
Ok, was cleaning up issues, let's reopen for reference then 👍

**Comment by diego-G** [comment] 2018-03-22 17:05
Add @IkerAlus for reference here

**Comment by IkerAlus** [comment] 2018-03-26 10:58
A similar approach as the one proposed here by OP is going to be developed for 2.0 release. 
Transaction's fee will depend on the size of the transaction size (which is highly correlated to the transaction type) with a minimum global possible fee (set in core to avoid spam attacks to the network).

A fee estimation algorithm is going to be implemented too which, as suggested here, will estimate the fees depending on the past blocks usage and network congestion.

All the details for the incoming 2.0 release will be set publicly on GitHub addressing this and other issues.

**Comment by shuse2** [comment] 2019-07-29 08:45
This will be introduced by https://github.com/LiskHQ/lips/blob/master/proposals/lip-0013.md.
For further discussion, please move to https://research.lisk.io/

**Closed by shuse2** 2019-07-29 08:45 UTC
Labels: framework/chain, status: discussion, type: enhancement
