### ISSUE TITLE
transaction:create with send flag errors with datapath flag

### ISSUE THREAD

**Issue by has5aan** [LiskHQ/lisk-sdk#8215] opened 2023-03-02 14:07 UTC
### Expected behavior
transaction:create with send flag should create and send the transaction, if data-path flag is configured to a value other than the default path. 

### Actual behavior
transaction:create with send flag and data-path configured to a value other than the default path throws;
`Error: Application at data path /Users/jupiter/.lisk/pos-mainchain is not running.`

### Steps to reproduce
Create a transaction with --send flag;
Example;
`./bin/run transaction:create pos unlock 10000000 --send --data-path ~/.lisk/pom`

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk SDK `development` branch.

Duplicate of #8144

**Comment by Incede** [comment] 2023-03-03 07:40
Probably duplicate of #8144

**Closed** 2023-03-03 09:47 UTC
Labels: type: bug
