### ISSUE TITLE
Node crashed multiple times without any error

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3353] opened 2019-04-15 10:44 UTC
### Expected behavior
- Node should log errors before crashing for tracability
- Since the issue is unknow due to no log info, we need to fix the issue once identified
### Actual behavior
```
2019-04-14 01:04:10 272: [dbg] 2019-04-14 01:04:10 | Transport->broadcastHeaders: Failed to notify peer about self - {"peer":"104.238.145.120:7001","err":"Error: Unable to match an address to the peer"}
2019-04-14 01:26:12 604: [inf] 2019-04-14 01:26:12 | Initializing controller
```
```
2019-04-14 01:50:40 593: [dbg] 2019-04-14 01:50:40 | Updated peer 46.101.111.1:7001 - {"state":2}
2019-04-14 01:53:01 985: [inf] 2019-04-14 01:53:01 | Initializing controller
```
### Which version(s) does this affect? (Environment, OS, etc...)
`1.6.0-rc.3`, Binary release

**Comment by michielmulders** [comment] 2019-04-15 13:36
Possible solution by adding a check to PID number which may not be the same when restarting:
```
  async _validatePidFile() {
        const pidPath = `${this.config.dirs.pids}/controller.pid`;
        const pidExists = await fs.pathExists(pidPath);
        if (pidExists) {
            const pid = parseInt(await fs.readFile(pidPath));
            const pidRunning = await isPidRunning(pid);
            if (pidRunning && pid !== process.pid) {
                this.logger.error(
                    `An instance of application "${
                        this.appLabel
                    }" is already running. You have to change application name to run another instance.`
                );
                throw new DuplicateAppInstanceError(this.appLabel, pidPath);
            }
        }
        await fs.writeFile(pidPath, process.pid);
    }
```

**Comment by michielmulders** [comment] 2019-04-16 15:30
Investigations currently suspended as the exact cause can be related to the application, `pm2`, or even external influence. If this happens again, further research is definitely needed to assure quality.

**Comment by shuse2** [comment] 2019-04-17 20:07
Closing because not reproducible

**Closed by shuse2** 2019-04-17 20:07 UTC
Labels: :dizzy: quality assurance, bug
