### ISSUE TITLE
Inconsistent block reward amount credited to bootstrap validator account without registered seed

### ISSUE THREAD

**Issue by Incede** [LiskHQ/lisk-sdk#8229] opened 2023-03-06 14:30 UTC
### Actual behavior
Without registering seed for an bootstrap validator, it receives the correct reward for the first block forged. The block generation is disabled immediately after and is enabled again after 206 blocks since then. Subsequently, the validator receives a reward when it forges a block as expected, however the amount credited to validator account is different compared to the amount when it forged the very first block.

### Expected behavior
The amount credited should be same as the amount credited after forging the first block.

### Steps to reproduce
`Without registering seed, check first block reward and stop block generation then enable after 206 blocks`
Optional - offset value can be changed in the config to avoid long waiting time (2160 blocks) :
```
	"modules": {
		"dynamicReward": {
		  "offset": 1
		}
	},
```

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by bobanm** [comment] 2023-03-20 09:57
I've set `modules.dynamicReward.offset = 1` in config, and assigned hash onions to 1 of the initial validators.

Then I observed the rewards minted and assigned to that validator:

```
round   block      amount
-------------------------
    1      64   500000000
    2     165   500000000
    3     266   500000000
    4     355   504500000
    5     499   509090909
    6     582   513775510
    7     662   518556701
    8     785   523437500
```

This is the expected behavior of Dynamic Reward module, and is not caused by whether or not a validator has registered hash onion seed.

The rewards per block are increasing because the number of available validators is constantly decreasing as of round 4. The reward calculation is handled in this section of Dynamic Reward module:

https://github.com/LiskHQ/lisk-sdk/blob/48b698dc63c44890bf384883cbc2a2e570f7a60c/framework/src/modules/dynamic_rewards/module.ts#L268-L278

**Closed by bobanm** 2023-03-20 09:57 UTC
Labels: type: bug
