### ISSUE TITLE
Transaction payload was rejected by the network node (dexGovernance:createProposal)

### ISSUE THREAD

**Issue by Daniel-Lightcurve** [LiskHQ/lisk-sdk#9141] opened 2023-11-10 16:33 UTC
### Expected behavior

Transaction submission should work fine without any error.
Used below endpoint for transaction submission
```
POST http://devnet-dex-service.liskdev.net:9901/api/v3/transactions
```

### Actual behavior

There's an error while submitting the transaction. (dexGovernance:createProposal)
```
{
    "error": true,
    "message": "Transaction payload was rejected by the network node: Cannot read properties of undefined (reading 'getLockedStakedAmount')."
}
```

### Steps to reproduce
Transaction Object:
```
{
command: "createProposal",
fee: 171000n,
id: Uint8Array [buffer: ArrayBuffer(0), byteLength: 0, byteOffset: 0, length: 0, Symbol(Symbol.toStringTag): 'Uint8Array'],
module: "dexGovernance",
nonce: 12n,
params: {
  type: 1,
  content: {
  {
    "text": "Dan's proposal description",
    "poolID": 00000000,
    "multiplier": 1,
    "metadata": {
        "title": "Dan's proposal",
        "author": "Daniel",
        "summary": "Dan's proposal summary"
     },
     "discussionsTo": "https://lisk.com"
  }
},
senderPublicKey: "c2d2e4b205a3197f13d7e2c5218391a06971437cad06ef51443522ba7c8e8fb5",
signatures: [Uint8Array(64)]
}
```

- Run a `dryrun` test using `POST http://devnet-dex-service.liskdev.net:9901/api/v3/transactions/dryrun`

Transaction payload
```0a0d646578476f7665726e616e6365120e63726561746550726f706f73616c180c20f8b70a2a20c2d2e4b205a3197f13d7e2c5218391a06971437cad06ef51443522ba7c8e8fb532200801121c0a01da120800000000000000001801220b0a01da1201da1a01da22003a40658c95db7f2a4a928ca805df8b0defff06186b184a3f42d00e78f2969bcf9a01fea8ea6f39b4b9cad51b63ca897d2d9fe1ec0f8ca219be52bede87aee3e13806```

- `dryrun` response:

```
{
    "data": {
        "result": -1,
        "status": "invalid",
        "events": [],
        "errorMessage": "Cannot read properties of undefined (reading 'getLockedStakedAmount')"
    },
    "meta": {}
}
```

**Comment by bobanm** [comment] 2023-11-16 13:10
Investigation showed the cause of the error was that Dex module did not register PoS method dependency correctly.

Also, the test cases used to test did not initialize `CreateProposalCommand` correctly.

Closing as non-issue.

**Closed by bobanm** 2023-11-16 13:10 UTC
Labels: type: bug
