### ISSUE TITLE
"lisk-core config:show" shows incorrect configuration

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-sdk#9175] opened 2023-12-05 22:23 UTC
### Expected behavior
The command `lisk-core config:show` should show the config that is currently in use by Lisk Core

### Actual behavior
The command `lisk-core config:show` shows the config file located in the default path (`~/.lisk/lisk-core/config/config.json`), even though a custom configuration file is specified in the start command.

### Steps to reproduce
- Setup a Lisk Core v4 node
- Create a custom config with some specific settings
- Run lisk-core with the custom config file. Eg:

```json
{
        "name": "lisk-core-v4",
        "script": "lisk-core start --network mainnet --config /home/lisk/custom-config.json"
}
```
- Run the command `lisk-core config:show`

## Important  
Please note that `lisk-core` _does_ actually utilize the custom configuration. The only issue that is presen is that an incorrect config is shown when executing the `lisk-core config:show` command.

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Core v4.0.1

**Comment by shuse2** [comment] 2023-12-08 12:49
i think config:show just shows what default configuration they have on lisk-core forthe particular network it's running. you can supply the --config option to get the resulting configuration

**Comment by shuse2** [comment] 2023-12-20 21:37
duplicate of #6335

**Closed by shuse2** 2023-12-20 21:37 UTC
Labels: type: bug
