### ISSUE TITLE
Analysis Fast Chain Switcher class to combine FCS mechanism logic

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-sdk#4276] opened 2019-09-18 09:28 UTC
### Description

Please describe what functionality is needed

### Motivation

Please describe why it is needed

### Acceptance Criteria

Please describe the conditions which must be met for this issue to close

**Comment by shuse2** [comment] 2019-09-18 09:44
Closing duplicate of #3777

**Closed by shuse2** 2019-09-18 09:44 UTC
Labels: type: spike
