### ISSUE TITLE
Use pre-hashing for signatures

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#7105] opened 2022-04-07 09:43 UTC
### LIP

- [Use pre-hashing for signatures](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0062.md)

### Description

This Epic provides technical specifications for `Use pre-hashing for signatures in Lisk`.  This includes transactions, block headers and certificate signatures. This allows signing to be performed on memory limited devices such as hardware wallets.

### Tasks

- [ ] #7102
- [ ] #7103
- [ ] #7104

**Comment by shuse2** [comment] 2022-04-08 07:38
This is duplicate of #6949

**Closed by shuse2** 2022-04-08 07:38 UTC
Labels: type: duplicate

**Comment by mitsuaki-u** [comment] 2022-04-08 07:42
> This is duplicate of #6949

Why not just close the other one keep this open since it had all the info? 🤔

**Comment by shuse2** [comment] 2022-04-08 08:00
@mitsuaki-u The link to the issue might have been used before, so I tried to keep the URL active 🙇
